### ISSUE TITLE
zphysics msvc build failing

### ISSUE THREAD

**Issue by hazeycode** [zig-gamedev/zig-gamedev#546]
Cross compiling from Linux (need to check Windows native build too!) gives many occurrences of the following:
```
error: argument unused during compilation: '-nostdinc++'
/home/chris/projects/zig-gamedev/libs/zphysics/libs/Jolt/Core/Core.h:11:11: error: 'winapifamily.h' file not found
 #include <winapifamily.h>
```

Regression introduced by adoption of Zig packager manager in https://github.com/zig-gamedev/zig-gamedev/commit/1a80092c18ddfeb31ec1252f47f71d344a7fd0ab

**Comment by hazeycode** [comment]
Can be built on windows-msvc using `zig build -Dtarget=x86_64-native`. Tracking cross-compilation separately.
