### ISSUE TITLE
Samples don't build on Windows 11 with Zig 0.13.0

### ISSUE THREAD

**Issue by LUK3D** [zig-gamedev/zig-gamedev#737]
Hello! I'm new to zig and I was trying to run the sample projects on my machine, but It doesn't run on zig version 0.13.0.

```bash 
D:\projects\zig\zig-gamedev> zig build physically_based_rendering_wgpu-run
.\AppData\Local\zig\p\12206d9a2b8a6036aeb178436f9c460d52d7d45efbc78d9387fb5256f0907e8b842b\build.zig:68:58: error: root struct of file 'Build.Step' has no member named 'MakeOptions'
            fn make(_: *std.Build.Step, _: std.Build.Step.MakeOptions) anyerror!void {}
                                           ~~~~~~~~~~~~~~^~~~~~~~~~~~
C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.13.0\lib\std\Build\Step.zig:1:1: note: struct declared here
id: Id,
^~
referenced by:
    activateEmsdkStep: ..\AppData\Local\zig\p\12206d9a2b8a6036aeb178436f9c460d52d7d45efbc78d9387fb5256f0907e8b842b\build.zig:69:10
    buildAndInstallSamplesWeb__anon_13371: D:\projects\zig\zig-gamedev\build.zig:197:44
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
..\AppData\Local\zig\p\1220293b509e9238e43828b00ee18e38eeace190ef844b74bf54e3db6e7da7398f4b\build.zig:43:16: error: no field or member function named 'addIncludePath' in 'Build.Step.TranslateC'
    translate_c.addIncludePath(b.path("libs/tracy/tracy"));
    ~~~~~~~~~~~^~~~~~~~~~~~~~~
C:\ProgramData\chocolatey\lib\zig\tools\zig-windows-x86_64-0.13.0\lib\std\Build\Step\TranslateC.zig:1:1: note: struct declared here
const std = @import("std");
^~~~~

```
### System details:
OS: Widnows11
CPU: Intel Core i9
GPU: NVIDIA GeForce RTX 4090
RAM: 64GB

**Comment by LUK3D** [comment]
Closing this because I realize that the samples require zig version 0.14.0-dev
